//! Lightweight binary / generated-file detection without parsing.

/// Any null byte in the first 512 bytes → binary. Single SIMD pass via memchr.
pub fn is_binary(buf: &[u8]) -> bool {
    let window = &buf[..buf.len().min(512)];
    memchr::memchr(0, window).is_some()
}

/// Check filename against known generated/lock files and extension patterns.
pub fn is_generated_by_name(name: &str) -> bool {
    if is_generated_filename(name) {
        return true;
    }
    is_generated_extension(name)
}

fn is_generated_filename(name: &str) -> bool {
    matches!(
        name,
        "package-lock.json"
            | "yarn.lock"
            | "pnpm-lock.yaml"
            | "Cargo.lock"
            | "composer.lock"
            | "Gemfile.lock"
            | "poetry.lock"
            | "go.sum"
            | "bun.lockb"
    )
}

fn is_generated_extension(name: &str) -> bool {
    let lower = name.to_lowercase();
    lower.ends_with(".min.js")
        || lower.ends_with(".min.css")
        || lower.ends_with(".pb.go")
        || lower.contains(".generated.")
        || lower.ends_with("_pb2.py")
        || lower.ends_with("_pb2_grpc.py")
        || lower.ends_with(".designer.cs")
        || lower.ends_with(".g.dart")
        || lower.ends_with(".gen.go")
        || lower.ends_with(".gen.ts")
}

const GENERATED_MARKERS: &[&[u8]] = &[
    b"@generated",
    b"DO NOT EDIT",
    b"Do not edit",
    b"do not edit",
    b"auto-generated",
    b"Auto-generated",
    b"AUTO-GENERATED",
    b"this file is generated",
    b"This file is generated",
    b"THIS FILE IS GENERATED",
    b"automatically generated",
    b"Automatically generated",
];

/// Scan first 512 bytes for generated-file markers using SIMD memmem.
pub fn is_generated_by_content(buf: &[u8]) -> bool {
    let window = &buf[..buf.len().min(512)];
    GENERATED_MARKERS
        .iter()
        .any(|m| memchr::memmem::find(window, m).is_some())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_binary() {
        assert!(is_binary(&[0u8, 1, 2, 3]));
        assert!(!is_binary(b"hello world"));
    }

    #[test]
    fn detects_generated_filename() {
        assert!(is_generated_by_name("package-lock.json"));
        assert!(is_generated_by_name("Cargo.lock"));
        assert!(!is_generated_by_name("Cargo.toml"));
    }

    #[test]
    fn detects_generated_content() {
        assert!(is_generated_by_content(b"// @generated by some-tool"));
        assert!(is_generated_by_content(b"# DO NOT EDIT - autogen"));
        assert!(!is_generated_by_content(b"// hand-written code"));
    }
}
